matrix:
  include:
    # use the built in venv for linux builds
    - os: linux
      language: python
      python: 3.6
    - os: osx
      language: cpp
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -C ethsnarks mac-dependencies ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nvm install --lts ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make -C ethsnarks ubuntu-dependencies ; fi
  - make -C ethsnarks PIP_ARGS= python-dependencies
script:
  - make
after_success:
  - make coverage
